# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datastream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='datastream.proto',
  package='NationalInstruments.DataStream',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64\x61tastream.proto\x12\x1eNationalInstruments.DataStream\x1a\x1bgoogle/protobuf/empty.proto\"*\n\x0fSubscriberToken\x12\x17\n\x0fsubscriberToken\x18\x01 \x01(\x05\"n\n\x0fTopicIdentifier\x12H\n\x0fsubscriberToken\x18\x01 \x01(\x0b\x32/.NationalInstruments.DataStream.SubscriberToken\x12\x11\n\ttopicName\x18\x02 \x01(\t\"3\n\tTopicData\x12\x11\n\ttopicName\x18\x01 \x01(\t\x12\x13\n\x0bmessageData\x18\x02 \x01(\x0c\"\x1b\n\tTopicList\x12\x0e\n\x06topics\x18\x01 \x03(\t2\xfd\x07\n\x11\x44\x61taStreamService\x12X\n\rAddSubscriber\x12\x16.google.protobuf.Empty\x1a/.NationalInstruments.DataStream.SubscriberToken\x12[\n\x10RemoveSubscriber\x12/.NationalInstruments.DataStream.SubscriberToken\x1a\x16.google.protobuf.Empty\x12Y\n\x0eSubscribeTopic\x12/.NationalInstruments.DataStream.TopicIdentifier\x1a\x16.google.protobuf.Empty\x12[\n\x10UnsubscribeTopic\x12/.NationalInstruments.DataStream.TopicIdentifier\x1a\x16.google.protobuf.Empty\x12t\n\x16ReadLatestTopicMessage\x12/.NationalInstruments.DataStream.TopicIdentifier\x1a).NationalInstruments.DataStream.TopicData\x12y\n\x19StartReadingTopicMessages\x12/.NationalInstruments.DataStream.SubscriberToken\x1a).NationalInstruments.DataStream.TopicData0\x01\x12\x63\n\x18StopReadingTopicMessages\x12/.NationalInstruments.DataStream.SubscriberToken\x1a\x16.google.protobuf.Empty\x12q\n\x13GetSubscribedTopics\x12/.NationalInstruments.DataStream.SubscriberToken\x1a).NationalInstruments.DataStream.TopicList\x12[\n\x16GetAllSubscribedTopics\x12\x16.google.protobuf.Empty\x1a).NationalInstruments.DataStream.TopicList\x12S\n\x0ePublishMessage\x12).NationalInstruments.DataStream.TopicData\x1a\x16.google.protobuf.Emptyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SUBSCRIBERTOKEN = _descriptor.Descriptor(
  name='SubscriberToken',
  full_name='NationalInstruments.DataStream.SubscriberToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscriberToken', full_name='NationalInstruments.DataStream.SubscriberToken.subscriberToken', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=123,
)


_TOPICIDENTIFIER = _descriptor.Descriptor(
  name='TopicIdentifier',
  full_name='NationalInstruments.DataStream.TopicIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscriberToken', full_name='NationalInstruments.DataStream.TopicIdentifier.subscriberToken', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topicName', full_name='NationalInstruments.DataStream.TopicIdentifier.topicName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=235,
)


_TOPICDATA = _descriptor.Descriptor(
  name='TopicData',
  full_name='NationalInstruments.DataStream.TopicData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topicName', full_name='NationalInstruments.DataStream.TopicData.topicName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messageData', full_name='NationalInstruments.DataStream.TopicData.messageData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=288,
)


_TOPICLIST = _descriptor.Descriptor(
  name='TopicList',
  full_name='NationalInstruments.DataStream.TopicList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topics', full_name='NationalInstruments.DataStream.TopicList.topics', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=317,
)

_TOPICIDENTIFIER.fields_by_name['subscriberToken'].message_type = _SUBSCRIBERTOKEN
DESCRIPTOR.message_types_by_name['SubscriberToken'] = _SUBSCRIBERTOKEN
DESCRIPTOR.message_types_by_name['TopicIdentifier'] = _TOPICIDENTIFIER
DESCRIPTOR.message_types_by_name['TopicData'] = _TOPICDATA
DESCRIPTOR.message_types_by_name['TopicList'] = _TOPICLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscriberToken = _reflection.GeneratedProtocolMessageType('SubscriberToken', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBERTOKEN,
  '__module__' : 'datastream_pb2'
  # @@protoc_insertion_point(class_scope:NationalInstruments.DataStream.SubscriberToken)
  })
_sym_db.RegisterMessage(SubscriberToken)

TopicIdentifier = _reflection.GeneratedProtocolMessageType('TopicIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _TOPICIDENTIFIER,
  '__module__' : 'datastream_pb2'
  # @@protoc_insertion_point(class_scope:NationalInstruments.DataStream.TopicIdentifier)
  })
_sym_db.RegisterMessage(TopicIdentifier)

TopicData = _reflection.GeneratedProtocolMessageType('TopicData', (_message.Message,), {
  'DESCRIPTOR' : _TOPICDATA,
  '__module__' : 'datastream_pb2'
  # @@protoc_insertion_point(class_scope:NationalInstruments.DataStream.TopicData)
  })
_sym_db.RegisterMessage(TopicData)

TopicList = _reflection.GeneratedProtocolMessageType('TopicList', (_message.Message,), {
  'DESCRIPTOR' : _TOPICLIST,
  '__module__' : 'datastream_pb2'
  # @@protoc_insertion_point(class_scope:NationalInstruments.DataStream.TopicList)
  })
_sym_db.RegisterMessage(TopicList)



_DATASTREAMSERVICE = _descriptor.ServiceDescriptor(
  name='DataStreamService',
  full_name='NationalInstruments.DataStream.DataStreamService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=320,
  serialized_end=1341,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddSubscriber',
    full_name='NationalInstruments.DataStream.DataStreamService.AddSubscriber',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SUBSCRIBERTOKEN,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveSubscriber',
    full_name='NationalInstruments.DataStream.DataStreamService.RemoveSubscriber',
    index=1,
    containing_service=None,
    input_type=_SUBSCRIBERTOKEN,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeTopic',
    full_name='NationalInstruments.DataStream.DataStreamService.SubscribeTopic',
    index=2,
    containing_service=None,
    input_type=_TOPICIDENTIFIER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UnsubscribeTopic',
    full_name='NationalInstruments.DataStream.DataStreamService.UnsubscribeTopic',
    index=3,
    containing_service=None,
    input_type=_TOPICIDENTIFIER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReadLatestTopicMessage',
    full_name='NationalInstruments.DataStream.DataStreamService.ReadLatestTopicMessage',
    index=4,
    containing_service=None,
    input_type=_TOPICIDENTIFIER,
    output_type=_TOPICDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartReadingTopicMessages',
    full_name='NationalInstruments.DataStream.DataStreamService.StartReadingTopicMessages',
    index=5,
    containing_service=None,
    input_type=_SUBSCRIBERTOKEN,
    output_type=_TOPICDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopReadingTopicMessages',
    full_name='NationalInstruments.DataStream.DataStreamService.StopReadingTopicMessages',
    index=6,
    containing_service=None,
    input_type=_SUBSCRIBERTOKEN,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSubscribedTopics',
    full_name='NationalInstruments.DataStream.DataStreamService.GetSubscribedTopics',
    index=7,
    containing_service=None,
    input_type=_SUBSCRIBERTOKEN,
    output_type=_TOPICLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllSubscribedTopics',
    full_name='NationalInstruments.DataStream.DataStreamService.GetAllSubscribedTopics',
    index=8,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TOPICLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PublishMessage',
    full_name='NationalInstruments.DataStream.DataStreamService.PublishMessage',
    index=9,
    containing_service=None,
    input_type=_TOPICDATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASTREAMSERVICE)

DESCRIPTOR.services_by_name['DataStreamService'] = _DATASTREAMSERVICE

# @@protoc_insertion_point(module_scope)
